{% set name = "srwpy" %}
{% set version = "0.2" %}
{% set sha256 = "5b4d6969deb5d3965b9dcad50ba509ef4ed0cf342b4380eb25760705b1f3dde3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Synchrotron-Radiation-Workshop/SRW/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-cmake_args-osx_arm64.patch  # [build_platform != target_platform]

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - gnuconfig   # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - fftw  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - wget  # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - fftw  # [win]
    - matplotlib-base
    - numpy
    - pillow
    - scipy

test:
  imports:
    - srwpy
    - srwpy.srwl_bl
    - srwpy.srwlib
    - srwpy.srwlpy
    - srwpy.uti_math

about:
  home: https://github.com/Synchrotron-Radiation-Workshop/SRW
  license: EPICS
  license_file: COPYRIGHT.txt
  summary: Synchrotron Radiation Workshop - Python
  description: |
    SRW is a physical optics computer code for calculation of detailed characteristics of
    Synchrotron Radiation (SR) generated by relativistic electrons in magnetic fields of
    arbitrary configuration and for simulation of the radiation wavefront propagation 
    through optical systems of beamlines.
  dev_url: https://github.com/Synchrotron-Radiation-Workshop/srw
  doc_url: https://synchrotron-radiation-workshop.github.io/srw

extra:
  recipe-maintainers:
    - hhslepicka 
    - mrakitin
