{% set name = "srwpy" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ochubar/SRW/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0b6c6f7829fe413909b2f3776af5471bec42a287789b2713912cf7117e416714

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - gnuconfig   # [unix]
    # - llvm-openmp  # [osx]
    # - libgomp      # [linux]
    - fftw  # [win]
    - fftw-static  # [osx or linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - wget  # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - fftw  # [win]
    - fftw-static  # [osx or linux]
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - scikit-learn
    - scipy

test:
  imports:
    - srwpy
    - srwpy.srwl_bl
    - srwpy.srwlib
    - srwpy.srwlpy
    - srwpy.uti_math

about:
  home: https://github.com/ochubar/SRW
  license: EPICS
  license_file: COPYRIGHT.txt
  summary: Synchrotron Radiation Workshop for Python
  description: |
    SRW is a physical optics computer code for calculation of detailed
    characteristics of Synchrotron Radiation (SR) generated by relativistic
    electrons in magnetic fields of arbitrary configuration and for simulation
    of the radiation wavefront propagation through optical systems of
    beamlines.
  dev_url: https://github.com/ochubar/SRW

extra:
  recipe-maintainers:
    - himanshugoel2797
    - hhslepicka
    - mrakitin
